### ISSUE TITLE
Function 'texturebumpenvmat' not found

### ISSUE THREAD

**Issue by caxanga334** [Regalis11/scpcb#85]
I've downloaded the source code and I get "function 'texturebumpenvmat' not found" error when I try to compile.
All decls files were added to userlibs.

**Comment by juanjp600** [comment]
SCPCB uses a modified version of Blitz3D, the binaries are included in this repo as "mavless_bin.zip". GO to your Blitz3D installation directory, and replace the bin folder with the contents of the zip.

**Comment by caxanga334** [comment]
The modified version wasn't working because I didn't extract the fmod.dll. The instructions (Instructions.txt) said to replace which made me think I only had to replace files that already exist.
Replaced files (this time including fmod.dll) and compile works now.
Thanks for the help.

**Comment by hlpdev** [comment]
Hey Regalis, sorry to reopen the issue, but I was wondering if you had the source code to the files in the `mavless_bin.zip` file because I am trying to port Blitz3D over to DirectX 9 but I want the game to be compatible with SCP: Containment Breach. Is there any way you could either send the source or direct me to where I could find it? Thanks, Hunter.
